version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: RSDuser
      POSTGRES_PASSWORD: Lamineyamal1
      POSTGRES_DB: LocalDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: 
