version: "3.8"

services:
  postgres-db:
    image: docker.uclv.cu/postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: RSDuser
      POSTGRES_PASSWORD: Lamineyamal1
      POSTGRES_DB: LocalDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    ports:
      - '3000:3000'
    env_file:
      - .env.local # Corregido el nombre del archivo
    command: sh -c "npm run start:dev"
    volumes: # Recomendado para desarrollo: montar el código
      - .:/app
      - /app/node_modules

  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - postgres-db

volumes:
  postgres_data: 
